version: "3.9"

services:
  pyverse:
    build:
      context: .
    image: pyverse
    container_name: pyverse
    ports:
      - "8787:8787"
    environment:
      DISABLE_AUTH: "true"
      USER: rstudio
    volumes:
      - .:/home/rstudio/project
    restart: unless-stopped
