services:
  pyverse:
    image: ghcr.io/a1eksb/reproducability:rstudio
    build: !reset null

  caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - .devcontainer/rstudio/Caddyfile:/etc/caddy/Caddyfile:ro
    depends_on:
      - pyverse
